name: ALZ AVD Accelerator Zone-0 Pipeline

on:
  push:
    branches:
      - "main"
    paths:
      - 'infra-as-code/zone-0.bicep'
      - 'carml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  Location: "norwayeast"
  AVDSubId: "a7693725-2adf-4eff-98eb-fc941246426d"
  ServiceObjectRGName: "alz-centrallogging"
  HubNetworkSubId: "0f18a4f9-2e78-43d0-b06a-6a490469a7a6"
  runNumber: ${{ github.run_number }}

jobs:
  CostEstimate:
    uses: TheCloudTheory/arm-estimator/.github/workflows/estimateFromUrl.yml@main
    with:
      rg: 'MyResourceGroup'
      environment: '' #Use empty string for repo level secrets
      templateFileURL: infra-as-code/zone-0..bicep
      templateParamFileURL: infra-as-code/parameters/zone-0.parameters.all.json
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: AVDSubId
  AVD_Bicep_HostPool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: OIDC Login to Tenant
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AVDSubId }}
          enable-AzPSSession: true

      - name: create zone-0
        id: create_zone-0
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.AVDSubId }}
          template: infra-as-code/zone-0..bicep
          parameters: infra-as-code/parameters/zone-0.parameters.all.json
          deploymentName: create_zone-0-${{ env.runNumber }}
          failOnStdErr: false
