name: ALZ AVD Accelerator Zone-1 Pipeline

on:
  push:
    branches:
      - "main"
    paths:
      - 'infra-as-code/parameters/*'
      - 'carml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  Location: "norwayeast"
  AVDSubId: "a7693725-2adf-4eff-98eb-fc941246426d"
  ServiceObjectRGName: "alz-centrallogging"
  HubNetworkSubId: "0f18a4f9-2e78-43d0-b06a-6a490469a7a6"
  runNumber: ${{ github.run_number }}

jobs:

  AVD_Bicep_HostPool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Create HostPool
        id: create_zone-0
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AVDSubId }}
          region: ${{ env.Location }}
          template: infra-as-code/zone-1.bicep
          parameters: infra-as-code/parameters/zone-1.parameters.all.json
          deploymentName: create_zone-1-${{ env.runNumber }}
          failOnStdErr: false
