name: ALZ AVD Accelerator Zone-0 Pipeline

on:
  push:
    branches:
      - "main"
    paths:
      - 'infra-as-code/zone-0.bicep'
      - 'carml'

env:
  Location: "norwayeast"
  AVDSubId: "a7693725-2adf-4eff-98eb-fc941246426d"
  ServiceObjectRGName: "alz-centrallogging"
  HubNetworkSubId: "0f18a4f9-2e78-43d0-b06a-6a490469a7a6"
  runNumber: ${{ github.run_number }}

jobs:
  bicep_tenant_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: create zone-0
        id: create_zone-0
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.AVDSubId }}
          template: infra-as-code/zone-0..bicep
          parameters: infra-as-code/parameters/zone-0.parameters.all.json
          deploymentName: create_zone-0-${{ env.runNumber }}
          failOnStdErr: false
